spring.application.name=appraisal


server.port=3000


spring.datasource.url=jdbc:mysql://localhost:3306/appraisal_db?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=a644395c0ce43e
spring.mail.password=78c5588ed60cf1
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=b7e2277ad5c7d36b4ca061f77643a95916131f86334d4332131debbf90d51577
jwt.expiration:28800000
